### ISSUE TITLE
Maintaining concat on npm

### ISSUE THREAD

**Issue by montanaflynn** [azer/concat#4]
Hey @azer, since I use concat a lot in some of my builds it would be nice if I could add it back to npm.

**Comment by epignosisx** [comment]
Yes, please. Can you transfer the project like you have done with some of your other modules.

**Comment by azer** [comment]
@montanaflynn added

**Comment by epignosisx** [comment]
Thanks @azer.

@montanaflynn could you let me know when you put it back in NPM? Looks like you will need to contact NPM, they have taken the *concat* name for security reasons:

https://www.npmjs.com/package/concat
